### ISSUE TITLE
[BUG] problem with browser.ssb.enabled

### ISSUE THREAD

**Issue by frasco66** [AdamXweb/WhiteSurFirefoxThemeMacOS#73]
**Describe the bug**
Hi guys, i have a problem with the firefox web app system. Once enabled browser.ssb.enabled and restart the browser, i don't see the three dots to turn the site in a web app

**To Reproduce**
1. Go to about:config and accept the risk
2. search for browser.ssb.enabled
3. activate and switch to true

**Expected behavior**
i expected to see the three dots in the right side of the search bar

**Screenshots**
![Immagine 2022-05-20 214918](https://user-images.githubusercontent.com/105946844/169600996-301deaeb-4082-47b3-91c0-f87f4f82324a.png)

after the restart of Firefox i can't see the three dots
![Immagine 2022-05-20 215012](https://user-images.githubusercontent.com/105946844/169601143-1d248ae7-b5be-4d85-a868-1b8466998cad.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Firefox version LAST
 
Thanks for the help guys

**Comment by AdamXweb** [comment]
I'm not familiar with SSB, could you send a screenshot of what three dots you are referring to?

**Comment by frasco66** [comment]
![Immagine 2022-05-21 175412](https://user-images.githubusercontent.com/105946844/169659540-64c1a362-5af4-409e-9be7-6afdd031e54f.png)

**Comment by AdamXweb** [comment]
I'm trying to debug this to figure out what the issue may be.
It sounds like you may have recently upgraded Firefox to Proton.
[This article](https://techdows.com/2021/05/firefox-proton-redesign-removes-page-actions-menu.html) explains that page actions have been removed.
This [bug report](https://support.mozilla.org/en-US/questions/1348811) on Mozilla states that SSB has been removed from V86.
It sounds like Firefox has updated due to an urgent vulnerability.
The ESR (Extended Service Release) has also been [updated](https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr) to support Proton (v91 +) which doesn't have the feature you're after.

Sorry I can't help further!
