### ISSUE TITLE
[FEAT] Make the navbar smaller when you start to scroll

### ISSUE THREAD

**Issue by michaeIwave** [AdamXweb/WhiteSurFirefoxThemeMacOS#77]
### Is your feature request related to a problem? If so, please describe.

It makes me frustrated that the top navigation bar is taking up a lot of screen space with the navigation bar most websites have

### Describe the solution you'd like

When you start to scroll you could make it so the tabs disappear and everything else except the URL bar get smaller and the opacity gets bigger

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by AdamXweb** [comment]
Hey @michaeIwave thanks for opening this feature request!

Firefox themes are quite limited with what you can do to customise the experience.
There may be an option with an extension that could help you hide the tabs or change the active css when you start to scroll, and i'd recommend asking the question on reddit under r/firefox or possibly r/firefoxcss!

Otherwise I'd suggest to use fullscreen mode and select hide toolbars.
<img width="434" alt="Screen Shot 2022-10-19 at 6 53 38 pm" src="https://user-images.githubusercontent.com/6800453/196630597-fec283f0-d63f-4176-a337-449a867b4276.png">
May not be exactly what you're after but it does give more screen real estate, and pops up again when you move your cursor to the top.

Have a great day
AdamXweb
